[build]
  command = "cp -R plugin-nextjs/ node_modules/@netlify/plugin-nextjs/ && cp -R functions/ node_modules/@netlify/functions/ && npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  included_files = ["posts/**"]
